name: zrj
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  icons_launcher: ^3.0.0
  stylish_bottom_bar: ^1.1.0
  flutter_screenutil: ^5.9.3
  form_validator: ^2.1.1
  flutter_svg: ^1.1.6
  responsive_sizer: ^3.3.1
  introduction_screen: ^3.1.14
  google_fonts: ^6.2.1
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  shared_preferences: any
  animated_page_transition: ^0.0.1+2
  country_code_picker: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
#  myfatoorah_flutter: ^3.1.4
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.1
  circular_countdown_timer: any
  change_app_package_name: ^1.4.0
  flutter_stripe: ^11.2.0
#  firebase_core: ^3.6.0
#  flutter_local_notifications: ^17.2.4
#  firebase_messaging: ^15.1.3
  googleapis_auth: ^1.6.0
  flutter_widget_from_html: ^0.9.1
  flutter_launcher_icons: ^0.14.1

  get_storage: ^2.1.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/images/final  ZRJ.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/final  ZRJ.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
